Fix files finding
yiisoft/yii-debug-api pull request #12
Opened 2020-10-18 10:51 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
| Tests pass?   | ✔️
| Depends on  | https://github.com/yiisoft/yii-debug/pull/61

:warning:  Before merge need to check in real integration
- [ ] Integration checked

2020-10-22 00:01 UTC, samdark commented
What problem is being fixed?

2020-10-22 06:00 UTC, rustamwin requested changes

2020-10-22 06:00 UTC, rustamwin commented on src/Repository/CollectorRepository.php
> +            $id = \basename($file, $fileType);
```suggestion
            $dir = \dirname($file);
            $id = \substr($dir, \strlen($this->path));
```

2020-10-22 06:00 UTC, rustamwin commented on src/Repository/CollectorRepository.php
>              if (!file_exists($file) || is_dir($file)) {
```suggestion
            if ($file === false || !file_exists($file) || is_dir($file)) {
```

2020-10-22 06:36 UTC, xepozz commented
> What problem is being fixed?

[This PR](https://github.com/yiisoft/yii-debug/pull/61) was changed directory hierarchy and now API won't find any debug-files.

2020-10-22 06:37 UTC, xepozz commented
We just need to use Storage abstraction instead of hard link to file storage.

2020-10-24 10:47 UTC, samdark approved these changes

2020-10-24 10:47 UTC, samdark commented
@rustamwin would you please check if the code works with the debugger?

2020-10-24 17:06 UTC, rustamwin commented
> @rustamwin would you please check if the code works with the debugger?

I checked. `DebugController::index` doesn't work as expected. Returns only one record.

2020-10-31 12:30 UTC, samdark commented
@xepozz would you please take a look?

2020-11-14 15:41 UTC, merged